name: mobile_dapp
description: An example how to create a mobile dApp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # WalletConnect
  walletconnect:
    path: ../../

  # Algorand
  algorand_dart: 0.0.2-beta.8

  # URL Launcher
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
